twig:
    form_theme: ['bootstrap_4_layout.html.twig']
    exception_controller: null
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        #Disponnible dans les view sous les params ex:{app_path_articles_images}
        app_path_articles_images: '%env(string:UPLOAD_PATH_ARTICLES)%'
        app_path_default_images: '%env(string:UPLOAD_PATH_DEFAULT)%'
        app_path_events_images: '%env(string:UPLOAD_PATH_EVENTS)%'

        site_name: 'Nomdesite'
        site_mail: 'Nomdesite@domain.fr'
        site_name_pretty: 'Nom de site'

        stripe_publish_key: 'stripe_publish_key'
        stripe_secret_key: 'stripe_secret_key'
