easy_admin:
  entities:
    Categorie:
      class: App\Entity\Categorie
      list:
        fields:
          - 'name'
          - 'slug'
          - {property: 'videos'}
          - {property: 'articles'}
      form:
          fields:
            - {property: 'name'}
            - {property: 'slug'}
