easy_admin:
  entities:
    Tags:
      class: App\Entity\Tag
      list:
        fields:
          - 'name'
          - 'slug'
          - {property: 'events'}
      form:
        fields:
          - {property: 'name'}
          - {property: 'slug'}
