easy_admin:
  entities:
    Tags:
      class: App\Entity\Tag
      list:
        fields:
          - 'name'
          - 'slug'
          - {property: 'event'}
      form:
        fields:
          - {property: 'name'}
          - {property: 'slug'}
