#index:
#    path: /
#    controller: App\Controller\DefaultController::index



endroid_qr_code:
  resource: "@EndroidQrCodeBundle/Resources/config/routes.yaml"
  prefix: /qr-code


homepage:
  path: /
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
  defaults:
    path: /fr
    permanent: true
